# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RACTestDemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks

  pod 'ReactiveCocoa', '~> 5.0.3'
  use_frameworks!

  # Pods for RACTestDemo

  target 'RACTestDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'RACTestDemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
